name: "Execute Listing"

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_EMAIL: "${{ github.actor }}@users.noreply.github.com"

on:
  workflow_dispatch:
    inputs:
      listing:
        type: string
        description: 'Listing number (e.g. 2.1)'
        required: true

jobs:
  execute-listing:
    name: "Executing listing ${{ github.event.inputs.listing }}"
    runs-on: ubuntu-latest
    steps:
      - id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Latest stable version of Go

      - name: Install Protoc and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      # Go build cache
      - name: Cache Go build
        uses: actions/cache@v3
        with:
          path: ${{ env.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Run
        run: |
          cd "$(find . -name listing_${{ github.event.inputs.listing }})"
          ./run.sh ${{ env.GITHUB_USERNAME }} ${{ env.GITHUB_EMAIL }}
